### ISSUE TITLE
iconsax.ttf is not valid font on Windows 11

### ISSUE THREAD

**Issue by bahmanworld** [lusaxweb/iconsax#19]
I've tried to install iconsax.ttf font on my computer that running Windows 11 build 22523.1000, i got this error...
![Not a valid font](https://drive.google.com/uc?export=download&id=1DaicaghimDLsNECciGyzhGZEqPuMACVK)

**Comment by carne8** [comment]
Same issue

**Comment by carne8** [comment]
I solve the problem,
I used [transfonter](https://transfonter.org) for regenerate the font

**Comment by bahmanworld** [comment]
> I solve the problem, I used [transfonter](https://transfonter.org) for regenerate the font

Tanx @carne8
It's working now...
