### ISSUE TITLE
Include iconsax.ttf in Flutter/Dart download folder

### ISSUE THREAD

**Issue by iqfareez** [lusaxweb/iconsax#2]
Hi. I'm download in [**Flutter**](http://iconsax.io/Iconsax/flutter.zip) format, but the zip only contains the `iconsax_icons.dart` file. No `.ttf` file found.

**Comment by iqfareez** [comment]
### Update: Found the `iconsax.ttf` in **css** folder. 

Icons are now working in Flutter. However, please include the `.ttf` in the flutter folder as well. Thanks,😄 

![image](https://user-images.githubusercontent.com/60868965/125322704-a2acad80-e370-11eb-9902-4fe05927bd38.png)

**Comment by luisDanielRoviraContreras** [comment]
https://pub.dev/packages/iconsax
