### ISSUE TITLE
how to use twotone with css

### ISSUE THREAD

**Issue by dohahelmy** [lusaxweb/iconsax#36]
I fixed CSS files as mentioned in a previous issue and the package works but can't use the effect of **twotone** icons.

![Screenshot 2023-04-30 160144](https://user-images.githubusercontent.com/17557397/235436061-db39967d-0901-4cb6-932f-27e01730a942.png)

Is there a way to fix this?

**Comment by ilyasbilgihan** [comment]
#23 I've just added a example usage, please check.

**Comment by dohahelmy** [comment]
This is so useful, thank you
