### ISSUE TITLE
How to use the bold variant?

### ISSUE THREAD

**Issue by ackzell** [lusaxweb/iconsax#6]
I tried different approaches to bring in the bold icons (the design I was given mixes both `linear` and `bold` styles).

I noticed the `/bold` folder on the downloads, but it might not be part of the font file?

**Comment by ilyasbilgihan** [comment]
I don't know why but for some reasons, some of the icons is not showing up correctly when using the method I mentioned [before](https://github.com/lusaxweb/iconsax/issues/5#issuecomment-910249352). 
For instance: 
- [x] `isax-dcube` (linear)
- [x] `isax-dcube1` (bulk - not working for some icons) 
- [ ] `isax-dcube2` (broken)
- [ ] `isax-dcube3` (two tone)
- [x] `isax-dcube4` (outline)
- [x] `isax-dcube5` (bold)

(Same thing happens for the most of the rest of the icons)

You can use bold icons by typing `5` to at the end of the icon name. For instance: `isax-messages-3` will be `linear` `isax-messages-35` will be `bold`. I didn't test it for every one of the icons, so there might be still not working icons.

I believe, those problems will be solved by fixing the `font files` in the `iconsax-css` folder.

**Comment by ackzell** [comment]
Thanks @ilyasbilgihan ! 
This worked great, for now only using the bold variation on my project but it is good to have this reference. 

Cheers!
